### ISSUE TITLE
Adding support for <img srcset>

### ISSUE THREAD

**Issue by f** [hwclass/jquery.responcy#1]
W3 has already a standard for this functionality. This lib may support this specification as a polyfill.

```
<img src="small.jpg" srcset="medium.jpg medium, large.jpg large">
```

or may be

```
<img src="small.jpg" srcset="medium.jpg 1000w, large.jpg 1920w">
```

WDYT @hwclass?

Sources:
- https://html.spec.whatwg.org/multipage/embedded-content.html#attr-img-srcset
- https://css-tricks.com/responsive-images-youre-just-changing-resolutions-use-srcset/

**Comment by hwclass** [comment]
Hi @f,

Cool idea to implement this API support for the browser. When I look at the links and also the specification on [caniuse](http://caniuse.com/#search=srcset), IE generally does not support this feature, so it could be nice to add.

Using like <img src="small.jpg" srcset="medium.jpg 1000w, large.jpg 1920w"> is OK but providing a [configuration constan](https://github.com/hwclass/jquery.responcy/blob/master/js/main.js#L6)t for the developer can be more useful during development I think. Otherwise, we can get some elements changing their sources for different screen size and so we have a chaos maybe.

I have seen this to be a tricky one:

`sizes="(min-width: 800px) 50vw, 100vw"` 

means that if the screen size gets widen, the source will be set with 50%, if smaller than 800 pixels, it goes 100 percent. This could be an option.

WDYT @f ?

Thanks ;)

**Comment by f** [comment]
Parsing `(min-width: 800px) 50vw, 100vw` string may be overkill for us, but it would be nicely functional.

**Comment by hwclass** [comment]
Yep @f, this can be cool to implement. 

Thanks.

**Comment by hwclass** [comment]
Merged @f. Ellerine sağlık ;)
